### ISSUE TITLE
Some POST requests for a file are failing in recent Chrome versions

### ISSUE THREAD

**Issue by Julian-Tovar** [php-webdriver/php-webdriver#984]
### Bug description

Good day team. I spent a whole workday chasing down this issue, and still I couldn't find the cause. All I know is this only happens in newer Chrome versions, for example in Chrome v102.0.5005.115. And this does not happen in older Chrome versions, for example in Chrome v97.0.4692.71. This happens with php-webdriver v1.12.1 which is the latest version as of today, I think.

The problem is in `lib/Remote/HttpCommandExecutor.php`, in the method `\Facebook\WebDriver\Remote\HttpCommandExecutor::execute`, when this line is executed:

`$raw_results = trim(curl_exec($this->curl));`

This sends a POST request to my Selenium standalone server v4.0.0-alpha-2 (which is the latest release I could find). If the request is to find a file, for example the file '/tmp/4c6e1abf-78a4-4b5c-923d-f651e70ff0d3/upload15440563679359095417file/h5ptest.zip', the POST request fails with 'invalid argument: File not found'. If you put a `file_exists($params['value'][0])` this returns `true`, meaning that the file exists (and if you stop execution, you can see that the file does exist).

I'm not 100% sure if I should report this here. Maybe I should have reported this to Chrome, or to Selenium. The reason why I'm posting this here, is because for me, the error appears in php-webdriver.

### How could the issue be reproduced

As a way to ensure the code from `\Facebook\WebDriver\Remote\HttpCommandExecutor::execute` is executed, you can do the following.

1. Get yourself a clone of https://github.com/moodle/moodle and install the site, following the instructions in https://docs.moodle.org/400/en/Installing_Moodle
2. Initialize the Behat site by doing at the root of the Moodle project: `php admin/tool/behat/cli/init.php`
3. Run the Behat tests in 'h5p/tests/behat/h5p_libraries.feature'
4. The tests with the Behat step "I upload ... file to ... filemanager" will fail. This step is the one that leads to the execution of `\Facebook\WebDriver\Remote\HttpCommandExecutor::execute` with a POST request for a file in '/tmp/'.

If you switch back to Chrome v97.0.4692.71 then all of these tests pass.

This is a screenshot of these tests failing in that step:
![Screenshot from 2022-06-15 21-53-56](https://user-images.githubusercontent.com/89230550/173981089-fb9da007-7d6e-48ec-9ac6-904a0a27cc9b.png)

The screenshot shows the stack trace, but just for reference, this is the stack trace in plain text:

```
Facebook\WebDriver\Exception\InvalidArgumentException: invalid argument: File not found : /tmp/b53b902e501a086e63759dac73b6eea0/upload11754737963443060613file/h5ptest.zip
  (Session info: chrome=102.0.5005.115) in /var/www/moodle/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:99
Stack trace:
#0 /var/www/moodle/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php(372): Facebook\WebDriver\Exception\WebDriverException::throwException()
#1 /var/www/moodle/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(585): Facebook\WebDriver\Remote\HttpCommandExecutor->execute()
#2 /var/www/moodle/vendor/php-webdriver/webdriver/lib/Remote/RemoteExecuteMethod.php(27): Facebook\WebDriver\Remote\RemoteWebDriver->execute()
#3 /var/www/moodle/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebElement.php(427): Facebook\WebDriver\Remote\RemoteExecuteMethod->execute()
#4 /var/www/moodle/vendor/oleg-andreyev/mink-phpwebdriver/src/WebDriver.php(884): Facebook\WebDriver\Remote\RemoteWebElement->sendKeys()
#5 /var/www/moodle/vendor/behat/mink/src/Element/NodeElement.php(261): OAndreyev\Mink\Driver\WebDriver->attachFile()
#6 /var/www/moodle/repository/upload/tests/behat/behat_repository_upload.php(155): Behat\Mink\Element\NodeElement->attachFile()
#7 /var/www/moodle/repository/upload/tests/behat/behat_repository_upload.php(56): behat_repository_upload->upload_file_to_filemanager()
#8 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(110): behat_repository_upload->i_upload_file_to_filemanager()
#9 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(64): Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall()
#10 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(138): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleCall()
#11 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(96): Behat\Testwork\Call\CallCenter->handleCall()
#12 /var/www/moodle/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(125): Behat\Testwork\Call\CallCenter->makeCall()
#13 /var/www/moodle/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(73): Behat\Behat\Tester\Runtime\RuntimeStepTester->testDefinition()
#14 /var/www/moodle/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableStepTester.php(74): Behat\Behat\Tester\Runtime\RuntimeStepTester->test()
#15 /var/www/moodle/vendor/moodlehq/behat-extension/src/Moodle/BehatExtension/EventDispatcher/Tester/ChainedStepTester.php(104): Behat\Behat\Hook\Tester\HookableStepTester->test()
#16 /var/www/moodle/vendor/moodlehq/behat-extension/src/Moodle/BehatExtension/EventDispatcher/Tester/MoodleEventDispatchingStepTester.php(101): Moodle\BehatExtension\EventDispatcher\Tester\ChainedStepTester->test()
#17 /var/www/moodle/vendor/behat/behat/src/Behat/Behat/Tester/StepContainerTester.php(59): Moodle\BehatExtension\EventDispatcher\Tester\MoodleEventDispatchingStepTester->test()
#18 /var/www/moodle/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeScenarioTester.php(76): Behat\Behat\Tester\StepContainerTester->test()
#19 /var/www/moodle/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php(74): Behat\Behat\Tester\Runtime\RuntimeScenarioTester->test()
#20 /var/www/moodle/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php(106): Behat\Behat\Hook\Tester\HookableScenarioTester->test()
#21 /var/www/moodle/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/IsolatingScenarioTester.php(69): Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->test()
#22 /var/www/moodle/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(84): Behat\Behat\Tester\Runtime\IsolatingScenarioTester->test()
#23 /var/www/moodle/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test()
#24 /var/www/moodle/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(74): Behat\Behat\Hook\Tester\HookableFeatureTester->test()
#25 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test()
#26 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test()
#27 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(75): Behat\Testwork\Hook\Tester\HookableSuiteTester->test()
#28 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test()
#29 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(73): Behat\Testwork\Tester\Runtime\RuntimeExercise->test()
#30 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test()
#31 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\Testwork\Ordering\OrderedExercise->test()
#32 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications()
#33 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute()
#34 /var/www/moodle/vendor/symfony/console/Command/Command.php(256): Behat\Testwork\Cli\Command->execute()
#35 /var/www/moodle/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#36 /var/www/moodle/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#37 /var/www/moodle/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\Component\Console\Application->doRun()
#38 /var/www/moodle/vendor/symfony/console/Application.php(166): Behat\Testwork\Cli\Application->doRun()
#39 /tmp/ide-behat.php(580): Symfony\Component\Console\Application->run()
#40 {main}
```

### Expected behavior

All the tests from step 4 should pass when using Chrome v102.0.5005.115.

Thank you very much.

**Comment by OndraM** [comment]
Hi, in order to check what is the error, please:

1) try using [latest version](https://www.selenium.dev/downloads/) of Selenium server (4.4 as of now)
2) also use the latest chrome/chromedrive (which is 104 now)
3) please fill the rest of the bug template, copy and fill especially this part:

```md
### Details
<!-- Please fill relevant following items: -->

* Php-webdriver version: <!-- You can run `composer show php-webdriver/webdriver` to find the version -->
* PHP version:  <!-- You can run `php -v` to find the version -->
* How do you start the browser driver or Selenium server:
  <!-- For example Selenium server, chromedriver command, Laravel Dusk, Docker, SauceLabs etc. -->
  <!-- If relevant, provide the complete command you use to start the browser driver or Selenium server -->
* Selenium server version: <!-- Relevant only if you use Selenium server -->
* Browser driver (chromedriver/geckodriver...) version: <!-- Run `chromedriver --version` or `geckodriver --version` -->
* Browser used + version:
* Operating system:
```

Thanks!

**Comment by Julian-Tovar** [comment]
It's fine, if you have this issue the workaround is to use Chrome 97 to run the tests, and do not update it.

**Comment by kirilkirkov** [comment]
@Julian-Tovar did you find a solution? i got this error only for some of my local files..
