### ISSUE TITLE
unknown error: missing or invalid columnNumber

### ISSUE THREAD

**Issue by QuestionDevelopment** [php-webdriver/php-webdriver#999]
Hello everyone,
I'm getting the following error and I don't know what to do :

```
2022/08/30 10:34:38 [error] 165727#165727: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\UnknownErrorException: unknown error: missing or invalid columnNumber
  (Session info: headless chrome=104.0.5112.101) in /var/www/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:139
Stack trace:
#0 /var/www/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php(372): Facebook\WebDriver\Exception\WebDriverException::throwException()
#1 /var/www/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(585): Facebook\WebDriver\Remote\HttpCommandExecutor->execute()
#2 /var/www/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(246): Facebook\WebDriver\Remote\RemoteWebDriver->execute()
#3 /var/www/vendor/symfony/panther/src/Client.php(529): Facebook\WebDriver\Remote\RemoteWebDriver->get()
#4 /var/www/project/example.php(25): Symfony\Component\Panther\Client->get()
#5 /var/www/api.php(128): project\example->article()
#6 /var/www/api.php(54): system\api->project()
#7 /var/www/public/" while reading response header from upstream, client: 22.22.22.22, server: example.url.com, request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "example.url.com"
```

Everything works perfectly when running the request via a standard web browser.  However, if I run the same request/data via curl this error occurs.  The code that produces the error is as follows : 

```
require_once $this->directory . 'vendor/autoload.php';
$driver = \Symfony\Component\Panther\Client::createChromeClient('/var/www/drivers/chromedriver');
$driver->get($_REQUEST['url']);
$driver->wait(20, 500)->until(function(){
    return $driver->executeScript('return document.readyState') == 'complete';
}, 'Error obtaining ready state');
$image_result = $driver->findElements(\Facebook\WebDriver\WebDriverBy::xpath('//img'));
```

**Comment by OndraM** [comment]
Hi @QuestionDevelopment , I'm so sorry, but for us to help you, you must fill the whole issue template. Without the information, we are unfortunately unable to provide help and trace the root cause.

Thanks for understanding, but feel free to open new issue with all the information filled.
